apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    name: node-service
    app: mynode
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: mynode
    name: node-service
