apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: mynode
spec:
  containers:
    - name: postgres
      image: postgres:alpine3.15
      ports:
        - containerPort: 5432
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: postgres-user
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-secret
            key: postgres-password
      - name: POSTGRES_HOST
        valueFrom:
          configMapKeyRef:
            name: postgres-configmap
            key: postgres-host
      - name: POSTGRES_DBNAME
      
