apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: mynode
spec:
  replicas: 3
  selector:
    matchLabels:
      name: postgres-pod
      app: mynode
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: mynode
    spec:
      containers:
        - name: postgres
          image: postgres:alpine3.15
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: postgres-password
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: postgres-host
          - name: POSTGRES_DBNAME  